name: Code Quality Gate

on:
  pull_request:
    branches: [main, making-pages]
  push:
    branches: [main, making-pages]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    env:
      CI: true
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type Check
        run: pnpm type-check

      - name: Prepare scripts
        run: |
          chmod +x .github/actions/duplicate-check/check.sh
          ls -l .github/actions/duplicate-check/check.sh  # Verify permissions

      - name: Duplicate Code Check
        id: dup-check
        uses: ./.github/actions/duplicate-check
        with:
          warning-threshold: 5
          failure-threshold: 10
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Post PR Comment
        if: |
          always() && 
          steps.dup-check.outcome == 'failure' && 
          github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comment } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `⚠️ Code Duplication Warning (${process.env.DUPLICATION_PERCENT}%)!\n` +
                    `Please review the [workflow run](${context.serverUrl}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DUPLICATION_PERCENT: ${{ steps.dup-check.outputs.duplication-percent }}

      - name: Fail build if over threshold
        if: steps.dup-check.outcome == 'failure'
        run: exit 1

      - name: Duplicate Code Check
        run: pnpm find-copies

      - name: Dependency Audit
        run: pnpm check-deps

      - name: Build Verification (if applicable)
        if: false # Enable if you have build step
        run: pnpm build && pnpm build:verify
