name: Code Quality Gate

on:
  pull_request:
    branches: [main, making-pages]
  push:
    branches: [main, making-pages]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    env:
      CI: true
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type Check
        run: pnpm type-check

      - name: Duplicate Code Check
        id: dup-check
        uses: ./.github/actions/duplicate-check
        with:
          warning-threshold: 10
          failure-threshold: 30
        continue-on-error: true

      - name: Post PR Comment
        if: |
          always() && 
          steps.dup-check.outcome == 'failure' && 
          github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('${{ github.workflow }}-${{ github.ref }}.log', 'utf8');
            // Use the report-duplication.js script here
            // Add custom formatting for the comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DUPLICATION-PERCENT: ${{ steps.dup-check.outputs.duplication-percent }}

      - name: Fail build if over threshold
        if: steps.dup-check.outcome == 'failure'
        run: exit 1

      - name: Duplicate Code Check
        run: pnpm find-copies

      - name: Dependency Audit
        run: pnpm check-deps

      - name: Build Verification (if applicable)
        if: false # Enable if you have build step
        run: pnpm build && pnpm build:verify
